version: '3'
services:
  desafiotecnico:
    image: danielsbelo/desafiotecnico
    ports:
      - '8080:8080'
    networks:
      - desafio-network
    depends_on:
      - desafiotecnico
  desafiotecnico:
    image: mysql:8
    networks:
      - desafio-network
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=desafiotecnico
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
networks:
  desafio-network: